//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Calendar.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public interface Calendar {
}
