//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class Customer extends  UserDatabase implements User {
	public String sessionId;
	public CustomerWallet wallet;
	public String getSessionId(Object String, String password) {
	
	}
	
	public CustomerWallet getwalletInfo() {

	}
	
	public ProductDatabase browseCatalog(String sessionId) {
	
	}
}
