//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CustomerWallet.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//


import java.sql.Timestamp;

public class CustomerWallet {
	private long creditCardNumber;
	private int securityCode;
	private Timestamp expirationDate;
}
