//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MaintenanceCalendar.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class MaintenanceCalendar implements Calendar {
	public Calendar calendar;
	public String checkTechnicalState() {
	
	}
}
