//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Manager.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class Manager extends UserDatabase implements User {
	public String sessionId;
	public String getSessionId(Object String, String password) {
	
	}
	
	public void fireTechnician() {
	
	}
}
