//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modifyProduct.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class modifyProduct {
	public void changeName(String name, String newName) {
	
	}
	
	public void changePrice(String name, double newValue) {
	
	}
}
