//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductDatabase.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class ProductDatabase {
	public String technicalState;
	public String id;
	public void scheduleMaintenance() {
	
	}
	
	public Boolean checkAvailability() {
	
	}
}
