//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class Product {
	public String name;
	public int pricePerDay;
	public enum equipmentClass{};
}
