//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductCalendar.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class ProductCalendar implements Calendar {
	public Calendar calendar;
	public Boolean checkIfReady() {
		return true;
	}
}
