//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductCatalog.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//


import java.util.List;

public class ProductCatalog {
	public List<Product> products;
	public void sortProducts() {
	
	}
}
