//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : rentEquipment.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class rentEquipment {
	public ProductDatabase rentEquipment(CustomerWallet wallet, Object productName) {

	}
}
