//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Technician.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class Technician implements User {
	public String sessionId;
	public ProductDatabase assignedJob;
	public String getSessionId(Object String, String password) {
		return "0";
	}
	
	public void reportRepair() {
	
	}
	
	public void repair() {
	
	}
}
