//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TechnicianUtility.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class TechnicianUtility {
	public void assignTechnician() {
	
	}
	
	public void changeTechnicalState() {
	
	}
}
