//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UserDatabase.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//


import java.util.List;

public class UserDatabase {
	public List<User> users;
	public void addNewUser(User user) {
	
	}
	
	public void removeUser(User user) {
	
	}
}
