//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public interface User {
	public String login = null;
	public String password = null;
}
