//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UserUtility.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class UserUtility {
	public String login(String login, String password) {

	}
}
