//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : websiteMain.java
//  @ Date : 14.05.2024
//  @ Author : 
//
//




public class websiteMain {
}
